version: "3.9"

services:
  api:
    build: 
      context: ./math_service
    container_name: math-api
    ports:
      - "8000:8000"
    volumes:
      #./math_service - local directory -> :/math-service - container directory which is set in Dockerfile in WORKDIR
      - ./math_service:/math-service                   # math-service from container math_api is the app folder: app’s code lives here;    
      - math-db:/math-service/persistent-db            # persistent-db directory in the math-service directory

    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped


volumes:
  math-db:

